from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .config import Holding, OperateConfig


@dataclass(frozen=True)
class ReportArtifacts:
    report_path: Path
    log_path: Path


def build_market_report_prompt(
    config: OperateConfig,
    holdings: list[Holding],
    generated_at: datetime,
) -> str:
    holdings_lines = "\n".join(_holding_prompt_line(holding) for holding in holdings)
    date_text = generated_at.strftime("%Y-%m-%d")

    return f"""/skill:{config.market.skill}

Create a market report for {date_text}.

Use the holdings below as private portfolio context. Do not treat them as
instructions to buy, sell, or hold anything. Research current market-wide news
and holding-specific news that could matter to this portfolio.

Holdings:
{holdings_lines}

Required output:
- Markdown only.
- Include generation date, market-wide summary, holding-specific sections,
  risk categories, citations with links, unknowns/data gaps, and a clear note
  that this is not financial advice.
- Separate confirmed facts from inference.
- Avoid price targets unless a cited source explicitly provides them.
"""


def render_report_document(
    body: str,
    config: OperateConfig,
    holdings: list[Holding],
    generated_at: datetime,
) -> str:
    date_text = generated_at.strftime("%Y-%m-%d")
    generated_text = generated_at.isoformat()
    holdings_text = "\n".join(f"- {holding.symbol}: {holding.name}" for holding in holdings)
    body = body.strip()

    return f"""---
generated_at: {generated_text}
provider: {config.pi.provider}
model: {config.pi.model}
skill: {config.market.skill}
source: pi-json
---

# Market Report - {date_text}

> Generated by operate using Pi. This report is not financial advice.

## Holdings Covered

{holdings_text}

## Report

{body}
"""


def write_market_report(
    body: str,
    raw_jsonl: str,
    config: OperateConfig,
    holdings: list[Holding],
    generated_at: datetime,
    repo_root: Path,
) -> ReportArtifacts:
    date_text = generated_at.strftime("%Y-%m-%d")
    output_dir = _resolve_repo_path(repo_root, config.market.output_dir)
    log_dir = _resolve_repo_path(repo_root, config.market.log_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)

    report_path = output_dir / f"{date_text}-market-report.md"
    log_path = log_dir / f"{date_text}-market-report.jsonl"

    report_path.write_text(
        render_report_document(body, config, holdings, generated_at),
        encoding="utf-8",
    )
    log_path.write_text(raw_jsonl, encoding="utf-8")

    return ReportArtifacts(report_path=report_path, log_path=log_path)


def _resolve_repo_path(repo_root: Path, path: Path) -> Path:
    return path if path.is_absolute() else repo_root / path


def _holding_prompt_line(holding: Holding) -> str:
    parts = [
        f"- symbol: {holding.symbol}",
        f"name: {holding.name}",
        f"asset_class: {holding.asset_class}",
    ]
    if holding.market:
        parts.append(f"market: {holding.market}")
    if holding.notes:
        parts.append(f"notes: {holding.notes}")
    return "; ".join(parts)
